# Generated by Django 3.0.6 on 2020-05-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='field',
        ),
        migrations.AddField(
            model_name='app',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
